steps:
  # Auth Service Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cov19-sample-project/auth-service:latest', './services/authentication-service/cov19.services.auth']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cov19-sample-project/auth-service:latest']
  # Deploy Kubernetes Auth Service Configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy-Auth-Web-Service
    args:
    - 'apply'
    - '-f'
    - './deployment/kubernetes/auth-service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west2-a'
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=c19-sample-web-services-cluster'
      - 'ConnectionStrings__AuthDb=$_AUTHDB_CONN_STRING'
      - 'Identity__Issuer=$_IDENTITY_ISSUER'
      - 'Identity__Origin=$_IDENTITY_ORIGIN'
  # Deploy Kubernetes Auth Database Configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy-Auth-Database-Service
    args:
    - 'apply'
    - '-f'
    - './deployment/kubernetes/auth-database.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west2-a'
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=c19-sample-web-services-cluster'