apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: gcr.io/cov19-sample-project/auth-service
        env: 
        - name: ConnectionString__AuthDb
          value: $_AUTHDB_CONN_STRING
        - name: Identity_Issuer
          value: $_IDENTITY_ISSUER
        - name: Identity_Origin
          value: $_IDENTITY_ORIGIN
        ports:
        - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: auth-service-load-balancer
  spec:
    selector:
      app: auth-service
    ports:
      - protocol: TCP
        port: 80
